# Generated by Django 5.0.1 on 2024-01-18 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0002_attendencedata_now_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendencedata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendencedata',
            name='start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
